name: HeroSneak
main: com.herocraftonline.squallseed31.herosneak.HeroSneak
version: 1.1.0.36
author: SquallSeeD31
commands:
  sneak:
    description: Toggle sneaking on or off.
    usage: /sneak [on|off] - Toggles (or sets) sneak status.