name: ${name}
main: ${project.packageName}.${name}
version: ${version}
website: ${url}
description: ${description}
author: SquallSeeD31
commands:
  sneak:
    description: Toggle sneaking on or off.
    usage: /sneak [on|off] - Toggles (or sets) sneak status.